services:
  nordvpn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - TOKEN=${NORDVPN_TOKEN}
      - CONNECT="--group p2p ch"
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.89.0/24  # So it can be accessed within the local network
    ports:
      - 8080:8080
      - 6878:6878      
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only  
    restart: unless-stopped

  acestream:
    image: ghcr.io/martinbjeldbak/acestream-http-proxy
    container_name: acestream
    depends_on:
      - nordvpn # Asegura que NordVPN se inicie antes
    environment:
      - ALLOW_REMOTE_ACCESS=yes # Permite acceso remoto a AceStream
    network_mode: "container:nordvpn" # Usa la red del contenedor NordVPN
    restart: unless-stopped
